# Generated by Django 2.0 on 2017-12-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
