# Generated by Django 2.0 on 2017-12-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_auto_20171214_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_of_graduation',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.CharField(max_length=100),
        ),
    ]
