# Generated by Django 2.0 on 2017-12-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_auto_20171214_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skills_choices',
            field=models.CharField(choices=[('p', 'Python'), ('d', 'Django'), ('drf', 'Django Rest Framework')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='education',
            name='developers',
            field=models.ManyToManyField(related_name='education', to='developers.Developers'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_graduation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empl_history',
            name='developers',
            field=models.ManyToManyField(related_name='employment_history', to='developers.Developers'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.CharField(max_length=100, verbose_name='other skills'),
        ),
    ]
