# Generated by Django 2.0 on 2017-12-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_auto_20171214_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skills',
            new_name='other_skills',
        ),
    ]
